// priority: 0

// Visit the wiki for more info - https://kubejs.com/
/* 
 * ServerEvents.recipes(callback) is a function that accepts another function,
 * called the "callback", as a parameter. The callback gets run when the 
 * server is working on recipes, and then we can make our own changes.
 * When the callback runs, it is also known as the event "firing". 
*/


// This array contains the IDs of items that we consider "uncraftable" in the Create mod.
const uncraftable = [
  'create:copper_backtank',
  'create:netherite_backtank',
  'create:potato_cannon',
  'create:extendo_grip',
  'create:wand_of_symmetry',
  'create:handheld_worldshaper',
  'create:schematicannon',
  'create:schematic_table',
  'create:encased_chain_drive',
  'create:adjustable_chain_gearshift',
  'create:chain_conveyor',
  'create:water_wheel',
  'create:large_water_wheel',
  'create:nozzle',
  'create:turntable',
  'create:cuckoo_clock',
  'create:empty_blaze_burner',
  'create:blaze_burner',
  'create:weighted_ejector',
  'create:chute',
  'create:smart_chute',
  'create:speedometer',
  'create:stressometer',
  'create:wooden_bracket',
  'create:metal_bracket',
  'create:fluid_valve',
  'create:smart_fluid_pipe',
  'create:hose_pulley',
  'create:portable_fluid_interface',
  'create:steam_engine',
  'create:steam_whistle',
  'create:mechanical_piston',
  'create:sticky_mechanical_piston',
  'create:piston_extension_pole',
  'create:gantry_carriage',
  'create:gantry_shaft',
  'create:mechanical_bearing',
  'create:clockwork_bearing',
  'create:rope_pulley',
  'create:elevator_pulley',
  'create:cart_assembler',
  'create:controller_rail',
  'create:linear_chassis',
  'create:secondary_linear_chassis',
  'create:radial_chassis',
  'create:sticker',
  'create:contraption_controls',
  'create:mechanical_drill',
  'create:deployer',
  'create:portable_storage_interface',
  'create:redstone_contact',
  'create:mechanical_harvester',
  'create:mechanical_plough',
  'create:mechanical_roller',
  'create:sail_frame',
  'create:white_sail',
  'create:mechanical_crafter',
  'create:sequenced_gearshift',
  'create:flywheel',
  'create:rotation_speed_controller',
  'create:track',
  'create:railway_casing',
  'create:schedule',
  'create:track_station',
  'create:track_signal',
  'create:track_observer',
  'create:controls',
  'create:brass_funnel',
  'create:andesite_tunnel',
  'create:brass_tunnel',
  'create:content_observer',
  'create:stockpile_switch',
  'create:item_hatch',
  'create:packager',
  'create:repackager',
  'create:package_frogport',
  'create:white_postbox',
  'create:stock_link',
  'create:stock_ticker',
  'create:redstone_requester',
  'create:factory_gauge',
  'create:display_link',
  'create:display_board',
  'create:nixie_tube',
  'create:rose_quartz_lamp',
  'create:redstone_link',
  'create:placard',
  'create:pulse_repeater',
  'create:pulse_extender',
  'create:pulse_timer',
  'create:powered_latch',
  'create:powered_toggle_latch',
  'create:wheat_flour',
  'create:dough',
  'create:cinder_flour',
  'create:sturdy_sheet',
  'create:brass_hand',
  'create:crafter_slot_cover',
  'create:electron_tube',
  'create:pulp',
  'create:cardboard',
  'create:precision_mechanism',
  'create:blaze_cake',
  'create:bar_of_chocolate',
  'create:sweet_roll',
  'create:chocolate_glazed_berries',
  'create:honeyed_apple',
  'create:builders_tea',
  'create:cardboard_sword',
  'create:copper_sheet',
  'create:brass_sheet',
  'create:iron_sheet',
  'create:golden_sheet',
  'create:minecart_coupling',
  'create:crafting_blueprint',
  'create:copper_diving_helmet',
  'create:netherite_diving_helmet',
  'create:copper_diving_boots',
  'create:netherite_diving_boots',
  'create:cardboard_helmet',
  'create:cardboard_chestplate',
  'create:cardboard_leggings',
  'create:cardboard_boots',
  'create:sand_paper',
  'create:sand_paper',
  'create:tree_fertilizer',
  'create:filter',
  'create:attribute_filter',
  'create:package_filter',
  'create:empty_schematic',
  'create:schematic_and_quill',
  'create:blaze_cake_base',
  'createdieselgenerators:engine_piston',
  'createdieselgenerators:wire_cutters',
  'createdieselgenerators:hammer',
  'createdieselgenerators:engine_silencer',
  'createdieselgenerators:diesel_engine',
  'createdieselgenerators:huge_diesel_engine',
  'createdieselgenerators:distillation_controller',
  'createdieselgenerators:oil_scanner',
  'createdieselgenerators:pumpjack_hole',
  'createdieselgenerators:pumpjack_bearing',
  'createdieselgenerators:pumpjack_crank',
  'createdieselgenerators:pumpjack_head',
  'createdieselgenerators:canister',
  'createdieselgenerators:oil_barrel',
  'createdieselgenerators:basin_lid',
  'createdieselgenerators:bulk_fermenter',
  'createdieselgenerators:andesite_girder',
  'createdieselgenerators:burner',
  'createdieselgenerators:chemical_turret',
  'createdieselgenerators:sheet_metal_panel',
  'createdieselgenerators:kelp_handle',
  'createdieselgenerators:lighter',
  'createdieselgenerators:chemical_sprayer',
  'createdieselgenerators:chemical_sprayer_lighter',
  'createdieselgenerators:entity_filter',
  'createdieselgenerators:mold'


];

//REMOVE ALL UNUSED CREATE STUFF
ServerEvents.recipes(event => {
  event.remove({ output:uncraftable })
  event.remove({ output: '#create:postboxes'})
  event.remove({ output: '#create:table_cloths'})
  event.remove({ output: '#create:toolboxes'})
  event.remove({ output: '#create:valve_handles'})
  event.remove({ output: '#create:seats'})

  


  console.log('Hello! The Create removal recipe event has fired!')
  })

console.info('Hello, World! (Loaded Create removal server scripts)')

